# Model arguments
model_name_or_path: mistralai/Mistral-7B-v0.1
model_revision: main
torch_dtype: bfloat16
use_flash_attention_2: false

# Data training arguments
chat_template: "{% for message in messages %}\n{% if message['role'] == 'user' %}\n{{ '<|user|>\n' + message['content'] + eos_token }}\n{% elif message['role'] == 'system' %}\n{{ '<|system|>\n' + message['content'] + eos_token }}\n{% elif message['role'] == 'assistant' %}\n{{ '<|assistant|>\n'  + message['content'] + eos_token }}\n{% endif %}\n{% if loop.last and add_generation_prompt %}\n{{ '<|assistant|>' }}\n{% endif %}\n{% endfor %}"
dataset_mixer: argilla/distilabel-capybara-dpo-7k-binarized
dataset_splits:
- train

preprocessing_num_workers: 8

# ORPOTrainer arguments
bf16: true
beta: 0.05
gradient_accumulation_steps: 1
gradient_checkpointing: true
hub_model_id: mistral-7b-orpo-sapo
hub_private_repo: True
learning_rate: 5.0e-6
log_level: info
logging_steps: 10
lr_scheduler_type: inverse_sqrt
max_length: 2048
max_prompt_length: 1792
token_generate_length: 256
num_train_epochs: 4
optim: adamw_bnb_8bit
output_dir: outputs
per_device_train_batch_size: 8
push_to_hub: true
report_to:
- wandb
save_strategy: "steps"
save_steps: 300
seed: 42
warmup_steps: 100
max_replay_buffer_size: 2000
sample_every_n_steps: 1
responses_per_prompt: 1
ema_beta: 0.5