# Model arguments
model_name_or_path: meta-llama/Meta-Llama-3-8B
model_revision: main
torch_dtype: bfloat16
use_flash_attention_2: true

# Data training arguments
chat_template: "{% for message in messages %}{{'<|im_start|>' + message['role'] + '\n' + message['content'] + '<|im_end|>' + '\n'}}{% endfor %}{% if add_generation_prompt %}{{ '<|im_start|>assistant\n' }}{% endif %}"

dataset_mixer: argilla/distilabel-capybara-dpo-7k-binarized
dataset_splits:
- train

preprocessing_num_workers: 8

# SFT trainer config
bf16: true
do_eval: false
evaluation_strategy: "no"
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
hub_model_id: llama-3-8b-sft
hub_private_repo: True
learning_rate: 2.0e-05
log_level: info
logging_steps: 50  
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 2048
num_train_epochs: 3
output_dir: otuputs
per_device_train_batch_size: 16
per_device_eval_batch_size: 8
push_to_hub: true
remove_unused_columns: true
report_to:
- wandb
save_strategy: "steps"
save_steps: 300
save_total_limit: null
seed: 42
warmup_ratio: 0.1